name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-15
            platform: darwin
            arch: x64
            flags: --sanitize address
          - os: macos-15
            platform: darwin
            arch: arm64
            flags: --sanitize address
          - os: macos-15
            platform: ios
            arch: arm64
          - os: macos-15
            platform: ios
            arch: arm64
            tags: -simulator
            flags: --simulator
          - os: macos-15
            platform: ios
            arch: x64
            tags: -simulator
            flags: --simulator
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: brew install llvm@20
      - run: npm install -g bare-make
      - run: npm install
      - run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --debug ${{ matrix.flags }}
      - run: bare-make build
      - run: bare-make test
        if: ${{ matrix.platform == 'darwin' }}
